### ISSUE TITLE
'View' dropdown entries show off-screen on Diagram page

### ISSUE THREAD

**Issue by RoddieKieley** [RoddieKieley/hawtio-artemis#1]
When connected to an Artemis 2.6.1 based broker I select the Diagram and correctly see the broker information. If however I select the 'View' dropdown to filter what is shown, the checkbox items appear off-screen on the bottom and I have to scrolldown to see the entries and toggle them.
![screenshot from 2018-08-20 09-49-39](https://user-images.githubusercontent.com/980979/44340157-84ff3900-a45e-11e8-82a6-0211ee49b720.png)

**Comment by abkieling** [comment]
When a checkbox is clicked, does the dropdown list close or stay open?
